# Generated by Django 5.1.1 on 2024-11-25 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="HuggingFaceRefineWeb",
            fields=[
                ("content", models.TextField(primary_key=True, serialize=False)),
                ("url", models.TextField(max_length=200)),
                ("timestamp", models.TextField()),
            ],
            options={
                "db_table": "base_huggingfacerefineweb",
            },
        ),
        migrations.DeleteModel(
            name="BubbleWords",
        ),
    ]
