# Generated by Django 5.1.1 on 2024-11-25 05:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_huggingfacerefineweb_delete_chatgptresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="huggingfacerefineweb",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="huggingfacerefineweb",
            name="url",
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="huggingfacerefineweb",
            table="huggingface-refineweb",
        ),
    ]
