# Generated by Django 5.1.1 on 2024-11-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_huggingfacerefineweb_timestamp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="huggingfacerefineweb",
            name="timestamp",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="huggingfacerefineweb",
            name="url",
            field=models.TextField(max_length=200),
        ),
    ]
